// <auto-generated />
using System;
using Emeraldine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Emeraldine.Infrastructure.Migrations
{
    [DbContext(typeof(BambooEnterpriseDbContext))]
    [Migration("20260501070645_AddBambooTechnicalProfilesAndManagementWindows")]
    partial class AddBambooTechnicalProfilesAndManagementWindows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Emeraldine.Domain.Entities.BambooManagementWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BambooSpeciesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndDay")
                        .HasColumnType("integer");

                    b.Property<int>("EndMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("RecommendedCulmAgeYearsHigh")
                        .HasColumnType("integer");

                    b.Property<int?>("RecommendedCulmAgeYearsLow")
                        .HasColumnType("integer");

                    b.Property<int?>("StartDay")
                        .HasColumnType("integer");

                    b.Property<int>("StartMonth")
                        .HasColumnType("integer");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BambooSpeciesId");

                    b.ToTable("BambooManagementWindows");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.BambooSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommonName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cultivar")
                        .HasColumnType("text");

                    b.Property<double>("DiameterHigh")
                        .HasColumnType("double precision");

                    b.Property<double>("DiameterLow")
                        .HasColumnType("double precision");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Habit")
                        .HasColumnType("integer");

                    b.Property<double>("HardinessLow")
                        .HasColumnType("double precision");

                    b.Property<double>("HeightHigh")
                        .HasColumnType("double precision");

                    b.Property<double>("HeightLow")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypicalShootingMonth")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BambooSpecies");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.BambooTechnicalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BambooSpeciesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FloweringIntervalYearsHigh")
                        .HasColumnType("integer");

                    b.Property<int?>("FloweringIntervalYearsLow")
                        .HasColumnType("integer");

                    b.Property<double?>("InternodeLengthHighCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("InternodeLengthLowCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("LeafLengthHighCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("LeafLengthLowCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("LeafWidthHighCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("LeafWidthLowCm")
                        .HasColumnType("double precision");

                    b.Property<string>("LightRequirement")
                        .HasColumnType("text");

                    b.Property<string>("MoisturePreference")
                        .HasColumnType("text");

                    b.Property<string>("NativeRange")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryUses")
                        .HasColumnType("text");

                    b.Property<double?>("RhizomeDepthHighCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("RhizomeDepthLowCm")
                        .HasColumnType("double precision");

                    b.Property<string>("ScentProfile")
                        .HasColumnType("text");

                    b.Property<double?>("SheathLengthHighCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SheathLengthLowCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SheathWidthHighCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SheathWidthLowCm")
                        .HasColumnType("double precision");

                    b.Property<string>("ShootEdibility")
                        .HasColumnType("text");

                    b.Property<double?>("SoilPhHigh")
                        .HasColumnType("double precision");

                    b.Property<double?>("SoilPhLow")
                        .HasColumnType("double precision");

                    b.Property<string>("SoilType")
                        .HasColumnType("text");

                    b.Property<string>("SwedishGrowerNotes")
                        .HasColumnType("text");

                    b.Property<string>("SwedishZone")
                        .HasColumnType("text");

                    b.Property<string>("TimberStrength")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("WallThicknessHighCm")
                        .HasColumnType("double precision");

                    b.Property<double?>("WallThicknessLowCm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BambooSpeciesId");

                    b.ToTable("BambooTechnicalProfiles");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Culm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DiameterCm")
                        .HasColumnType("double precision");

                    b.Property<int>("EmergenceYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HarvestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HeightMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PhysicalTagCode")
                        .HasColumnType("text");

                    b.Property<Guid>("PlantUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlantUnitId");

                    b.ToTable("Culms");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Harvest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CulmId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HarvestType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlantUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CulmId");

                    b.HasIndex("PlantUnitId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.InventoryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BambooSpeciesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExchangeRateToSek")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PotVolumeLiters")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdateReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BambooSpeciesId");

                    b.ToTable("InventoryBatches");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.MaterialBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HarvestId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaterialType")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingMethod")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HarvestId");

                    b.ToTable("MaterialBatches");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.PlantUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentLocationDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PlantCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlantedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InventoryBatchId");

                    b.ToTable("PlantUnits");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("InventoryBatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("SKU")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InventoryBatchId");

                    b.HasIndex("MaterialBatchId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.BambooManagementWindow", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.BambooSpecies", "BambooSpecies")
                        .WithMany()
                        .HasForeignKey("BambooSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BambooSpecies");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.BambooTechnicalProfile", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.BambooSpecies", "BambooSpecies")
                        .WithMany()
                        .HasForeignKey("BambooSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BambooSpecies");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Culm", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.PlantUnit", "PlantUnit")
                        .WithMany()
                        .HasForeignKey("PlantUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantUnit");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Harvest", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.Culm", "Culm")
                        .WithMany()
                        .HasForeignKey("CulmId");

                    b.HasOne("Emeraldine.Domain.Entities.PlantUnit", "PlantUnit")
                        .WithMany()
                        .HasForeignKey("PlantUnitId");

                    b.Navigation("Culm");

                    b.Navigation("PlantUnit");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.InventoryBatch", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.BambooSpecies", "BambooSpecies")
                        .WithMany()
                        .HasForeignKey("BambooSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BambooSpecies");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.MaterialBatch", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.Harvest", "Harvest")
                        .WithMany()
                        .HasForeignKey("HarvestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Harvest");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Order", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emeraldine.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.PlantUnit", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.InventoryBatch", "InventoryBatch")
                        .WithMany()
                        .HasForeignKey("InventoryBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryBatch");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.Product", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.InventoryBatch", "InventoryBatch")
                        .WithMany()
                        .HasForeignKey("InventoryBatchId");

                    b.HasOne("Emeraldine.Domain.Entities.MaterialBatch", "MaterialBatch")
                        .WithMany()
                        .HasForeignKey("MaterialBatchId");

                    b.Navigation("InventoryBatch");

                    b.Navigation("MaterialBatch");
                });

            modelBuilder.Entity("Emeraldine.Domain.Entities.StockItem", b =>
                {
                    b.HasOne("Emeraldine.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
